name: Release - Linux-x86_64-gnu
description: |
  Build and release the Linux x86_64-gnu binary.

runs:
    using: "composite"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: x86_64-unknown-linux-gnu
          args: "--release"
          strip: true

      - name: Create ZIP (Posix)
        shell: bash
        run: |
          zip -j mvt-server-linux-gnu-x86_64.zip target/x86_64-unknown-linux-gnu/release/mvt-server
          mkdir -p builds
          mv mvt-server-linux-gnu-x86_64.zip builds/

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: release-builds
          path: builds/mvt-server-linux-gnu-x86_64.zip
          retention-days: 1
