name: Build and Release

on:
  push:
    tags-ignore:
      - 'nightly*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build Windows Release
        uses: ./.github/workflows/deployment/release/windows

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build MacOs Release
        uses: ./.github/workflows/deployment/release/macos

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build Linux Release
        uses: ./.github/workflows/deployment/release/linux

  # build-freebsd:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4.2.2
  #
  #     - name: Build FreeBSD Release
  #       uses: ./.github/workflows/deployment/release/freebsd
  #

  deploy:
    name: Deploy Release
    needs:
      - build-windows
      - build-macos
      - build-linux
      # - build-freebsd
    runs-on: ubuntu-24.04
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v4.3.0
      with:
        name: release-builds-windows
        path: builds

    - name: Download macOS artifact
      uses: actions/download-artifact@v4.3.0
      with:
        name: release-builds-macos
        path: builds

    - name: Download Linux artifact
      uses: actions/download-artifact@v4.3.0
      with:
        name: release-builds-linux
        path: builds

    # - name: Download FreeBSD artifacts
    #   uses: actions/download-artifact@v4.3.0
    #   with:
    #     name: release-builds-freebsd
    #     path: builds

    - uses: ncipollo/release-action@v1.16.0
      with:
        artifacts: "builds/*.zip"
